## Importing the libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
x_train=pd.read_csv('gisette_train.data',delimiter=' ')
x_train

,550,0,495,0.1,0.2,0.3,0.4,976,0.5,0.6,...,0.3856,0.3857,991.153,991.154,0.3858,0.3859,0.3860,0.3861,983.409,Unnamed: 5000
0,0,0,0,0,0,0,0,976,0,0,...,475,0,991,0,0,991,0,0,0,NaN
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,0,0,742,0,0,0,0,684,0,956,...,0,0,0,0,0,674,0,0,838,NaN
3,0,0,0,0,0,0,0,608,0,979,...,0,0,828,0,0,0,0,0,0,NaN
4,0,0,0,0,0,0,0,0,0,0,...,0,0,983,0,0,0,0,0,0,NaN
5,0,0,0,0,0,0,0,0,0,0,...,0,0,541,0,0,945,0,0,0,NaN
6,0,0,991,0,0,0,0,0,0,0,...,0,0,0,0,0,631,0,0,483,NaN
7,0,0,983,0,0,652,0,0,0,0,...,0,0,0,0,983,991,0,0,0,NaN
8,0,0,0,0,0,0,0,770,0,983,...,0,0,684,705,0,0,0,0,656,NaN
9,0,0,0,0,0,0,0,607,0,995,...,991,0,991,603,0,0,0,0,0,NaN
10,0,0,0,0,0,0,0,816,0,0,...,0,0,0,0,0,0,0,0,0,NaN
11,0,0,0,0,0,0,0,495,0,0,...,0,0,991,0,0,0,0,0,0,NaN
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
14,0,0,742,0,0,0,0,983,0,0,...,0,0,0,0,0,0,0,0,709,NaN
15,0,0,0,0,0,0,0,0,0,890,...,0,0,427,0,0,0,0,0,0,NaN
16,0,0,0,0,0,0,0,451,0,793,...,0,0,0,0,0,0,0,0,0,NaN
17,0,0,0,0,0,0,0,0,0,995,...,0,0,976,991,0,980,0,0,0,NaN
18,0,0,991,0,0,0,676,952,0,0,...,0,0,812,0,0,0,0,521,749,NaN
19,0,0,0,0,0,464,0,0,0,0,...,0,0,0,615,0,0,0,0,0,NaN
20,0,0,0,0,0,0,0,0,0,578,...,0,0,976,0,0,0,0,0,591,NaN
21,0,0,0,0,0,0,316,645,0,0,...,0,0,843,682,0,0,0,0,0,NaN
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,504,0,NaN
23,590,0,0,0,0,0,0,0,0,0,...,0,0,991,0,980,0,0,0,0,NaN
24,0,0,0,0,0,0,0,0,0,0,...,0,0,719,0,0,0,0,886,0,NaN
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
26,0,0,0,0,0,510,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,634,0,NaN
28,805,0,0,0,0,0,0,696,0,0,...,0,0,0,0,0,0,0,0,0,NaN
29,0,0,0,0,0,0,0,719,0,0,...,0,0,999,0,0,845,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5969,0,0,0,0,0,0,0,749,0,0,...,0,0,0,0,0,0,0,0,0,NaN
5970,0,0,0,0,0,0,763,0,0,0,...,0,0,976,0,664,540,0,952,0,NaN
5971,0,0,983,0,0,0,0,0,0,0,...,898,0,0,0,496,863,0,0,0,NaN
5972,0,0,0,0,0,0,0,906,0,0,...,0,0,535,0,0,0,0,0,0,NaN
5973,0,0,544,0,0,0,0,0,0,0,...,991,0,0,0,0,933,0,0,0,NaN
5974,0,0,0,0,0,0,0,0,0,0,...,661,0,0,0,0,0,0,0,0,NaN
5975,501,0,940,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
5976,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,699,0,0,0,NaN
5977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,968,0,906,0,NaN
5978,0,0,0,0,0,0,0,784,0,0,...,0,0,0,0,0,0,0,0,0,NaN
5979,0,0,0,0,0,0,0,999,0,0,...,0,0,666,0,0,511,0,0,0,NaN
5980,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,991,0,0,0,NaN
5981,0,0,0,0,0,0,0,0,0,735,...,0,0,0,0,0,948,0,0,0,NaN
5982,0,0,0,0,0,0,0,0,0,0,...,854,0,933,0,0,0,0,0,0,NaN
5983,0,0,650,0,473,0,0,991,0,0,...,464,0,0,0,0,0,0,983,0,NaN
5984,980,0,0,0,0,0,0,0,0,550,...,0,0,0,0,0,0,0,0,0,NaN
5985,0,0,0,0,0,0,0,886,0,0,...,0,0,0,0,0,517,0,0,0,NaN
5986,777,0,0,0,0,0,0,983,0,0,...,0,0,859,0,0,0,0,0,0,NaN
5987,0,0,0,0,0,0,0,508,0,0,...,995,0,0,764,687,0,0,0,0,NaN
5988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
5989,0,0,0,0,0,875,0,785,0,983,...,0,0,948,0,0,0,0,0,0,NaN
5990,0,0,0,0,0,704,0,0,0,0,...,0,0,855,0,0,0,0,0,0,NaN
5991,0,0,0,0,0,0,472,976,0,0,...,0,0,0,0,0,0,0,486,0,NaN
5992,0,0,0,0,0,0,0,0,0,368,...,0,0,608,0,0,987,0,0,0,NaN
5993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
5994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,783,0,0,0,NaN
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,921,0,886,0,NaN
5996,0,0,0,0,0,758,0,0,0,522,...,901,0,0,0,0,980,0,0,0,NaN
5997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,690,0,0,0,0,0,NaN
5998,0,0,991,0,0,0,0,0,0,0,...,0,0,288,0,0,972,0,0,991,NaN

In [7]:
x_train=x_train.drop('Unnamed: 5000',1)

In [10]:
y_train=pd.read_csv('gisette_train.labels')

In [11]:
y_train

      1
0    -1
1     1
2     1
3     1
4     1
5     1
6     1
7    -1
8     1
9    -1
10   -1
11    1
12    1
13   -1
14   -1
15   -1
16    1
17   -1
18   -1
19    1
20   -1
21    1
22    1
23    1
24   -1
25   -1
26    1
27    1
28   -1
29   -1
...  ..
5969  1
5970  1
5971  1
5972  1
5973 -1
5974 -1
5975  1
5976 -1
5977 -1
5978  1
5979 -1
5980  1
5981  1
5982 -1
5983 -1
5984 -1
5985  1
5986 -1
5987 -1
5988  1
5989  1
5990 -1
5991  1
5992 -1
5993  1
5994 -1
5995  1
5996 -1
5997 -1
5998 -1

[5999 rows x 1 columns]

In [12]:
x_test=pd.read_csv('gisette_valid.data',delimiter=' ')
x_test

,688,0,0.1,0.2,0.3,0.4,0.5,952,0.6,870,...,0.4436,0.4437,0.4438,0.4439,0.4440,494,0.4441,769.1,0.4442,Unnamed: 5000
0,778,758,0,0,0,0,0,708,0,991,...,0,0,770,0,0,0,0,0,0,NaN
1,469,0,816,0,0,0,0,0,0,0,...,0,0,467,0,0,0,417,0,0,NaN
2,0,0,0,0,0,571,991,983,0,983,...,0,0,0,0,0,0,0,0,0,NaN
3,0,0,0,0,0,0,0,949,0,991,...,0,0,0,0,0,0,0,976,0,NaN
4,0,0,0,0,0,0,0,0,0,450,...,0,0,0,0,0,800,0,0,0,NaN
5,0,0,0,0,0,0,0,976,0,0,...,964,0,0,0,0,0,0,0,0,NaN
6,0,0,552,0,0,0,0,956,0,0,...,0,0,976,0,0,983,0,0,0,NaN
7,0,0,0,0,0,0,0,0,0,0,...,367,0,0,0,0,983,0,0,0,NaN
8,0,0,0,0,0,0,0,777,0,0,...,392,0,0,991,0,0,0,0,0,NaN
9,0,0,0,0,0,0,0,520,0,0,...,0,0,0,0,0,0,0,706,0,NaN
10,976,0,0,0,0,0,0,0,0,999,...,0,0,0,0,0,0,0,0,0,NaN
11,0,0,0,0,0,0,0,823,0,581,...,0,0,0,686,0,0,0,0,0,NaN
12,0,0,0,0,0,0,0,952,0,0,...,0,0,976,0,0,0,0,0,0,NaN
13,659,0,0,0,0,0,0,987,0,976,...,0,0,0,0,0,0,0,0,0,NaN
14,976,0,0,0,0,0,0,0,294,0,...,0,0,0,0,0,983,0,0,0,NaN
15,0,0,0,0,0,0,0,0,0,0,...,0,0,840,819,0,0,0,0,0,NaN
16,976,0,0,0,0,0,0,0,0,0,...,0,0,0,0,498,0,0,0,980,NaN
17,0,0,0,0,0,0,0,824,0,0,...,0,0,0,505,0,0,0,0,0,NaN
18,0,0,0,0,0,0,0,0,0,0,...,0,0,890,878,0,784,0,0,0,NaN
19,0,0,0,0,976,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
20,0,0,0,0,0,0,0,941,0,0,...,0,0,0,0,0,816,0,0,0,NaN
21,413,0,0,0,0,715,0,0,0,0,...,0,0,898,0,0,991,0,0,0,NaN
22,0,0,0,0,0,0,0,0,0,809,...,0,0,0,0,0,0,0,0,0,NaN
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
24,0,0,0,0,0,0,0,512,0,0,...,0,0,801,0,0,0,0,0,0,NaN
25,0,0,0,0,0,0,0,0,0,0,...,0,0,537,0,0,0,0,0,0,NaN
26,976,0,0,0,0,0,0,910,0,581,...,0,0,701,0,0,976,0,0,0,NaN
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
28,0,0,0,0,0,0,0,976,0,0,...,0,0,876,0,0,777,0,0,0,NaN
29,0,0,727,0,0,983,0,0,0,0,...,0,0,722,987,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,968,0,0,0,0,NaN
970,991,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
971,0,0,0,0,0,0,0,0,0,0,...,0,0,902,0,0,0,616,650,933,NaN
972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,886,875,NaN
973,0,0,441,0,0,0,0,498,0,0,...,0,0,0,0,0,0,0,0,913,NaN
974,0,0,0,0,0,913,0,689,0,757,...,0,0,661,0,0,695,0,0,0,NaN
975,0,0,0,0,0,0,0,832,0,0,...,0,0,0,0,0,871,0,0,0,NaN
976,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
977,0,0,0,0,0,0,0,945,0,0,...,839,0,806,936,501,490,0,0,0,NaN
978,0,0,0,0,0,0,0,0,0,0,...,0,0,991,0,0,828,0,0,0,NaN
979,0,0,0,0,0,0,835,0,0,0,...,0,0,0,0,0,0,0,0,983,NaN
980,0,0,0,0,0,0,0,0,0,0,...,0,0,983,0,0,0,0,0,976,NaN
981,792,0,0,0,0,0,0,641,0,0,...,0,0,0,999,666,0,0,0,0,NaN
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
983,983,0,539,0,0,0,0,593,0,0,...,0,0,0,0,0,0,0,0,0,NaN
984,991,0,517,0,0,0,0,0,0,0,...,0,0,0,0,0,557,0,0,0,NaN
985,0,0,363,0,0,0,0,523,0,0,...,0,0,0,0,0,991,0,456,0,NaN
986,0,0,0,0,0,0,0,0,0,0,...,0,0,991,0,0,0,0,529,0,NaN
987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,972,0,0,0,NaN
988,0,0,0,0,0,0,743,808,0,0,...,0,0,0,0,0,941,0,0,0,NaN
989,991,0,0,0,0,0,0,0,0,0,...,691,0,0,0,0,0,0,0,0,NaN
990,0,0,425,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,474,0,NaN
991,0,0,723,0,0,0,0,960,0,983,...,548,0,652,0,0,980,0,0,785,NaN
992,0,0,0,0,0,0,0,749,0,991,...,0,0,983,0,815,999,0,0,0,NaN
993,0,0,0,0,0,0,0,890,0,0,...,0,0,0,0,0,0,0,0,0,NaN
994,0,511,0,0,0,0,0,0,0,0,...,0,0,852,0,0,0,0,0,0,NaN
995,0,0,599,0,0,0,0,910,0,0,...,0,0,0,0,0,0,0,0,707,NaN
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,742,NaN
997,0,0,0,0,0,0,0,968,0,0,...,0,0,773,0,0,0,0,0,0,NaN
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,952,0,0,0,NaN

In [13]:
y_test=pd.read_csv('gisette_valid.labels')

In [14]:
y_test

     1
0    1
1   -1
2    1
3    1
4   -1
5   -1
6   -1
7   -1
8   -1
9    1
10   1
11  -1
12   1
13  -1
14   1
15   1
16   1
17   1
18   1
19  -1
20   1
21   1
22   1
23   1
24  -1
25   1
26   1
27  -1
28   1
29   1
..  ..
969 -1
970  1
971 -1
972  1
973 -1
974 -1
975 -1
976  1
977  1
978  1
979  1
980  1
981 -1
982  1
983 -1
984 -1
985  1
986  1
987  1
988 -1
989 -1
990  1
991 -1
992  1
993 -1
994 -1
995  1
996  1
997 -1
998 -1

[999 rows x 1 columns]

In [15]:
x_test.columns

Index(['688', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '952', '0.6', '870',
       ...
       '0.4436', '0.4437', '0.4438', '0.4439', '0.4440', '494', '0.4441',
       '769.1', '0.4442', 'Unnamed: 5000'],
      dtype='object', length=5001)

In [16]:
x_test=x_test.drop('Unnamed: 5000',1)

In [17]:
y_test

     1
0    1
1   -1
2    1
3    1
4   -1
5   -1
6   -1
7   -1
8   -1
9    1
10   1
11  -1
12   1
13  -1
14   1
15   1
16   1
17   1
18   1
19  -1
20   1
21   1
22   1
23   1
24  -1
25   1
26   1
27  -1
28   1
29   1
..  ..
969 -1
970  1
971 -1
972  1
973 -1
974 -1
975 -1
976  1
977  1
978  1
979  1
980  1
981 -1
982  1
983 -1
984 -1
985  1
986  1
987  1
988 -1
989 -1
990  1
991 -1
992  1
993 -1
994 -1
995  1
996  1
997 -1
998 -1

[999 rows x 1 columns]

## Training the model with PCA

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
pca=PCA(n_components=20)
input=[['scale',StandardScaler()],['mode',pca]]
pipe=Pipeline(input)
res1=pipe.fit_transform(x_train)
res2=pipe.transform(x_test)
print(res1)

[[ 18.56089049  -9.8496447   -9.59366646 ...  -9.21320157  -0.77780297
    0.04953262]
 [ 10.25716678 -13.19219765 -11.09080858 ...  -1.61990075  -1.84743025
   -1.19527547]
 [ 11.00329861  -3.27711827   4.35372596 ...  11.19197079  -0.40789417
  -10.21284801]
 ...
 [  4.03509774 -12.64523281  -6.05891252 ...  -1.59618856   0.28558022
   -5.20331134]
 [ -4.20165661 -13.10935509   3.83819851 ...   3.65002832  -2.65843708
   -2.39807704]
 [ -4.86781252  15.43445836  -4.11382399 ...   1.25983619  -4.18117989
   -2.3671607 ]]

In [19]:
XprincipalDf = pd.DataFrame(res1)
XprincipalDf_t = pd.DataFrame(res2)

## Logistic Regression

In [20]:
from sklearn.metrics import accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
input=[('mode',LogisticRegression())]
print(input)
pipe=Pipeline(input)
res=pipe.fit(XprincipalDf,y_train)

yhat=res.predict(XprincipalDf)
print(yhat)
print(accuracy_score(y_train,yhat))
print(classification_report(y_train,yhat))

[('mode', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False))]
[-1  1  1 ... -1 -1 -1]
0.9528254709118187
              precision    recall  f1-score   support

          -1       0.95      0.95      0.95      3000
           1       0.95      0.95      0.95      2999

    accuracy                           0.95      5999
   macro avg       0.95      0.95      0.95      5999
weighted avg       0.95      0.95      0.95      5999

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:

yhat=res.predict(XprincipalDf_t)
print(yhat)
print(accuracy_score(y_test,yhat))
print(classification_report(y_test,yhat))

[ 1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1  1 -1  1  1  1  1  1 -1  1  1  1  1
 -1  1  1 -1  1  1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1  1
 -1 -1 -1 -1 -1  1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1 -1
  1  1  1 -1 -1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1
 -1  1  1 -1 -1  1  1  1  1 -1  1  1 -1  1 -1  1 -1  1  1 -1 -1 -1  1 -1
  1 -1  1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1  1  1  1 -1  1  1  1 -1  1  1
  1 -1  1  1 -1  1 -1  1  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1  1
  1  1  1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1  1  1  1 -1  1  1  1
 -1  1 -1 -1 -1  1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1 -1  1
 -1  1 -1  1  1 -1  1 -1 -1  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1  1  1
 -1 -1 -1 -1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1 -1  1  1 -1 -1 -1 -1
  1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1  1 -1  1 -1 -1 -1  1 -1
  1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1 -1 -1 -1 -1 -1  1  1  1  1  1 -1
 -1  1  1 -1 -1  1 -1 -1 -1  1 -1  1 -1  1  1 -1 -1  1 -1 -1  1 -1  1  1
 -1  1  1  1  1 -1 -1 -1 -1  1  1  1 -1  1 -1  1 -1 -1 -1  1  1  1 -1  1
  1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1 -1  1
 -1 -1 -1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1  1 -1 -1 -1
  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1  1  1  1 -1  1 -1  1  1 -1 -1  1 -1 -1
  1 -1  1  1  1  1  1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1 -1  1 -1  1 -1
 -1  1 -1 -1  1  1 -1  1  1  1 -1  1 -1  1 -1 -1  1  1  1  1 -1 -1  1  1
  1 -1 -1  1  1 -1  1  1 -1 -1 -1  1 -1 -1  1  1  1  1 -1  1  1 -1 -1  1
 -1 -1 -1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1
  1 -1 -1  1 -1  1  1 -1  1 -1  1 -1  1 -1 -1 -1 -1  1  1  1  1  1 -1 -1
 -1  1 -1  1  1 -1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1
  1  1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1 -1 -1 -1  1 -1  1  1 -1  1
  1 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1
  1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1  1 -1
  1 -1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1  1 -1 -1  1
  1 -1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1 -1 -1
 -1  1 -1  1 -1 -1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1 -1 -1 -1 -1  1  1
  1  1  1  1  1 -1 -1  1 -1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1
 -1  1 -1  1 -1 -1  1 -1  1 -1  1  1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1
  1 -1 -1  1  1 -1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1
 -1  1 -1  1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1
 -1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1  1 -1 -1 -1  1 -1
 -1 -1  1  1  1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1  1  1  1 -1  1 -1 -1 -1
  1  1 -1  1  1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1 -1  1  1  1 -1  1 -1
  1 -1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1  1  1  1
  1 -1 -1 -1 -1  1  1  1  1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1
  1  1 -1 -1 -1 -1  1 -1  1 -1  1 -1  1  1  1 -1 -1  1  1 -1  1  1  1 -1
  1 -1  1  1 -1  1  1  1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1  1 -1
 -1  1  1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
0.9529529529529529
              precision    recall  f1-score   support

          -1       0.96      0.95      0.95       500
           1       0.95      0.96      0.95       499

    accuracy                           0.95       999
   macro avg       0.95      0.95      0.95       999
weighted avg       0.95      0.95      0.95       999

## KNN

In [25]:
from sklearn.metrics import accuracy_score,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
input=[('mode',KNeighborsClassifier(n_neighbors=7))]
print(input)
pipe=Pipeline(input)
res=pipe.fit(XprincipalDf,y_train)

yhat=res.predict(XprincipalDf)
print(yhat)
print(accuracy_score(y_train,yhat))
print(classification_report(y_train,yhat))

[('mode', KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform'))]

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\pipeline.py:356: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)

[-1  1  1 ... -1 -1 -1]
0.9814969161526921
              precision    recall  f1-score   support

          -1       0.98      0.99      0.98      3000
           1       0.99      0.98      0.98      2999

    accuracy                           0.98      5999
   macro avg       0.98      0.98      0.98      5999
weighted avg       0.98      0.98      0.98      5999

In [26]:

yhat=res.predict(XprincipalDf_t)
print(yhat)
print(accuracy_score(y_test,yhat))
print(classification_report(y_test,yhat))

[ 1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1  1 -1  1  1  1  1  1 -1  1  1  1  1
 -1  1  1 -1  1  1  1 -1  1  1  1 -1  1 -1 -1  1 -1  1  1 -1 -1  1 -1  1
 -1 -1 -1 -1 -1  1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1 -1
  1  1  1 -1 -1  1  1 -1  1  1  1 -1  1 -1  1 -1  1  1 -1 -1 -1  1 -1  1
 -1 -1  1 -1 -1  1  1  1  1 -1  1  1 -1  1 -1  1 -1  1  1 -1 -1 -1  1 -1
  1 -1  1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1 -1  1  1
  1 -1  1  1 -1  1 -1  1  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1  1
  1  1  1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1  1  1  1 -1  1  1  1
 -1  1 -1 -1 -1  1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1 -1  1
 -1  1 -1  1  1 -1  1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1  1  1
  1 -1 -1 -1  1  1 -1  1  1  1  1  1 -1  1 -1  1  1 -1  1  1 -1 -1  1 -1
  1 -1  1  1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1  1 -1  1 -1 -1 -1  1 -1
  1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1
 -1  1  1 -1 -1  1 -1 -1 -1  1 -1  1 -1  1  1 -1 -1  1 -1 -1  1 -1  1  1
 -1  1  1  1  1 -1 -1 -1  1  1  1  1 -1  1 -1  1 -1 -1 -1  1  1  1 -1  1
  1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1 -1  1
 -1 -1 -1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1 -1 -1 -1  1
  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1  1  1  1 -1  1 -1  1  1 -1 -1  1 -1 -1
  1 -1  1  1  1  1  1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1 -1  1  1  1 -1
 -1  1 -1 -1  1 -1 -1  1  1  1 -1  1 -1  1 -1 -1  1  1  1  1 -1 -1  1  1
  1 -1 -1  1  1 -1  1  1 -1 -1 -1  1 -1 -1  1 -1  1  1 -1  1  1 -1 -1 -1
 -1 -1  1 -1  1 -1  1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1 -1  1  1
  1 -1 -1  1 -1  1  1 -1  1 -1  1 -1  1 -1 -1 -1 -1  1  1  1  1  1 -1 -1
 -1  1 -1  1  1 -1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1
 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1
  1 -1  1 -1 -1 -1 -1  1  1  1  1  1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1
  1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1  1 -1
  1 -1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1  1 -1 -1  1 -1 -1  1
  1 -1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1  1  1  1 -1  1  1 -1 -1 -1
 -1  1 -1  1 -1 -1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1 -1 -1 -1 -1  1  1
  1  1  1  1  1 -1 -1  1 -1  1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1
 -1  1 -1  1 -1 -1  1 -1  1 -1  1  1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1
 -1 -1 -1  1  1 -1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1
 -1  1 -1  1  1 -1  1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1
 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1  1 -1  1 -1  1  1  1 -1 -1 -1  1  1
 -1 -1  1  1  1 -1 -1  1 -1 -1 -1  1 -1  1 -1 -1  1  1  1 -1  1 -1 -1 -1
  1  1 -1  1  1  1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1  1  1 -1  1 -1
  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1  1 -1  1  1  1
  1 -1 -1 -1 -1  1  1  1  1  1 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1
  1  1 -1 -1 -1 -1  1 -1  1 -1  1 -1  1  1  1 -1 -1  1  1 -1  1  1  1 -1
  1 -1  1  1 -1  1  1  1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1  1 -1
 -1  1  1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
0.9679679679679679
              precision    recall  f1-score   support

          -1       0.96      0.98      0.97       500
           1       0.98      0.96      0.97       499

    accuracy                           0.97       999
   macro avg       0.97      0.97      0.97       999
weighted avg       0.97      0.97      0.97       999